<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <!-- デフォルトは Exe（Linux, macOS 用） -->
        <OutputType>Exe</OutputType>
        <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    </PropertyGroup>

    <!-- Windows 向けビルドの場合は WinExe に変更 -->
    <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('win'))">
        <OutputType>WinExe</OutputType>
    </PropertyGroup>

    <!-- プロジェクト参照（マルチターゲットの外側評価を避けるため net10.0 に固定） -->
    <ItemGroup>
        <ProjectReference Include="..\KyoshinEewViewer\KyoshinEewViewer.csproj">
            <SetTargetFramework>TargetFramework=net10.0</SetTargetFramework>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="App.axaml.cs">
          <DependentUpon>%(Filename)</DependentUpon>
        </Compile>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Update="Views\MainWindow.axaml.cs">
          <DependentUpon>%(Filename)</DependentUpon>
        </Compile>
        <Compile Update="Views\SplashWindow.axaml.cs">
          <DependentUpon>%(Filename)</DependentUpon>
        </Compile>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <None Update="libs\linux-x64\libbass.so" Condition="$(RuntimeIdentifier)=='' or $(RuntimeIdentifier)=='linux-x64'">
            <Link>libbass.so</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="libs\linux-arm64\libbass.so" Condition="$(RuntimeIdentifier)=='' or $(RuntimeIdentifier)=='linux-arm64'">
            <Link>libbass.so</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="libs\osx\libbass.dylib" Condition="$(RuntimeIdentifier)=='' or $(RuntimeIdentifier.StartsWith('osx'))">
            <Link>libbass.dylib</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="libs\win-x64\bass.dll" Condition="$(RuntimeIdentifier)=='' or $(RuntimeIdentifier)=='win-x64'">
            <Link>bass.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="libs\win-arm64\bass.dll" Condition="$(RuntimeIdentifier)=='win-arm64'">
            <Link>bass.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
